from PIL import Image
import os

SPRITE_W = 40
SPRITE_H = 40
OUTPUT_FILE = "sprites.py"
INPUT_FILES = ["walk_0.png", "walk_1.png"]


def png_to_mono_hlsb(path):
    """
    Convert a PNG to a MONO_HLSB bytearray.
    - Resizes to SPRITE_W x SPRITE_H if needed
    - Converts to pure 1-bit black & white (threshold at 128)
    - Packs pixels MSB-first, left-to-right per row
    - Black pixel (dark)  → 0 bit  (ink on e-paper)
    - White pixel (light) → 1 bit  (no ink on e-paper)
    """
    img = Image.open(path).convert("L")  # grayscale

    if img.size != (SPRITE_W, SPRITE_H):
        print("  Resizing {} from {}x{} to {}x{}".format(
            path, img.size[0], img.size[1], SPRITE_W, SPRITE_H))
        img = img.resize((SPRITE_W, SPRITE_H), Image.NEAREST)

    pixels = img.load()
    stride = SPRITE_W // 8  # bytes per row = 5 for 40px wide
    buf = bytearray(stride * SPRITE_H)

    for y in range(SPRITE_H):
        for x in range(SPRITE_W):
            lum = pixels[x, y]
            # threshold: dark pixels become ink (0), light pixels stay white (1)
            bit = 0 if lum < 128 else 1
            byte_idx = y * stride + x // 8
            bit_pos  = 7 - (x % 8)  # MSB first (HLSB)
            if bit == 1:
                buf[byte_idx] |= (1 << bit_pos)
            # 0 bits are already 0 from bytearray initialisation

    return buf


def buf_to_python_literal(buf, name):
    """Format a bytearray as a compact Python bytearray literal."""
    hex_bytes = ", ".join("0x{:02X}".format(b) for b in buf)
    lines = []
    # Wrap at ~72 chars per line for readability
    chunk = 12  # hex bytes per line
    rows  = [list(buf[i:i+chunk]) for i in range(0, len(buf), chunk)]
    inner = ",\n    ".join(
        ", ".join("0x{:02X}".format(b) for b in row) for row in rows
    )
    lines.append("{} = bytearray([\n    {}\n])".format(name, inner))
    return "\n".join(lines)


def main():
    frames = []
    for i, fname in enumerate(INPUT_FILES):
        if not os.path.exists(fname):
            print("ERROR: {} not found. Place it next to this script.".format(fname))
            return
        print("Converting {}...".format(fname))
        buf = png_to_mono_hlsb(fname)
        frames.append((fname, buf))
        print("  → {} bytes ({} x {} pixels, MONO_HLSB)".format(
            len(buf), SPRITE_W, SPRITE_H))

    with open(OUTPUT_FILE, "w") as f:
        f.write("# sprites.py — auto-generated by convert_sprites.py\n")
        f.write("# DO NOT EDIT — re-run convert_sprites.py to regenerate\n")
        f.write("# Format: MONO_HLSB, {}x{} pixels, {} bytes per frame\n\n".format(
            SPRITE_W, SPRITE_H, (SPRITE_W // 8) * SPRITE_H))
        f.write("SPRITE_W = {}\n".format(SPRITE_W))
        f.write("SPRITE_H = {}\n\n".format(SPRITE_H))

        for i, (fname, buf) in enumerate(frames):
            var_name = "WALK_{}".format(i)
            f.write("# Frame {} — source: {}\n".format(i, fname))
            f.write(buf_to_python_literal(buf, var_name))
            f.write("\n\n")

        f.write("# All frames as a list — index with FRAMES[frame_idx]\n")
        f.write("FRAMES = [{}]\n".format(
            ", ".join("WALK_{}".format(i) for i in range(len(frames)))))

    print("\nDone! {} written.".format(OUTPUT_FILE))
    print("Upload sprites.py to your ESP32 root via Thonny.")


if __name__ == "__main__":
    main()
